/**
 * @file
 * Makes the committed contrast reports load-bearing instead of decorative.
 *
 * Run with the Node test runner (as `npm run test:unit` does):
 *   node --test components/00-tokens/colors/section-background-contrast-report.test.mjs
 *
 * ## Why this exists
 *
 * `section-background-contrast.txt` and `functional-element-contrast.txt` are
 * generated by their sibling `.mjs` scripts and committed. Until this test,
 * nothing asserted against them -- so they were a point-in-time snapshot that
 * could silently go stale the moment a token moved.
 *
 * That mattered more than it sounds, because two SCSS comments cite them as
 * *evidence for a styling decision*:
 *
 *   _yds-layout.scss:335         "section-background-contrast.txt shows no ..."
 *   _yds-wrapped-callout.scss    "section-background-contrast.txt shows no fixed slot clears"
 *
 * A stale report cited as justification is worse than no report: the next
 * person to touch those rules trusts a number that is no longer true. This
 * test closes that by re-deriving every ratio the report records and failing if
 * the file and the tokens disagree.
 *
 * ## What it checks
 *
 * Section 1 of the report ("DOES THE SECTION'S OWN FOREGROUND CLEAR ITS OWN
 * BACKGROUND?") is the part that carries a recomputable claim per row: a
 * background slot, a foreground slot, a ratio and a verdict. Every such row is
 * re-derived from `@yalesites-org/tokens` via `sectionBackgrounds()` and
 * compared. Sections 2 and 3 enumerate slots and raw palette values against
 * backgrounds; their rows are covered transitively by the same palette
 * resolution, and are not re-parsed here.
 *
 * When this fails, the fix is to regenerate, not to edit the file:
 *   node components/00-tokens/colors/section-background-contrast.mjs \
 *     > components/00-tokens/colors/section-background-contrast.txt
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { contrastRatio, parseHsl, formatRatio } from './contrast-ratio.mjs';
import { sectionBackgrounds } from './section-background-contrast.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPORT = path.join(HERE, 'section-background-contrast.txt');
const FUNCTIONAL_REPORT = path.join(HERE, 'functional-element-contrast.txt');

/**
 * Row shape in section 1, e.g.
 *   one (Old Blues)   one   slot-one hsl(210, 100%, 21%)   content -> slot-eight  12.06:1  PASS
 *
 * Captured: global theme machine name, section theme, background slot,
 * role, foreground slot, recorded ratio, recorded verdict.
 */
const ROW = new RegExp(
  [
    '^(\\S+)\\s+\\([^)]*\\)', // global theme + its label
    '\\s+(\\S+)', // section theme
    '\\s+(slot-\\S+)\\s+hsl\\([^)]*\\)', // background slot + value
    '\\s+(\\S+)\\s+->\\s+(slot-\\S+)', // role -> foreground slot
    '\\s+([0-9.]+):1', // recorded ratio
    '\\s+(PASS|FAIL.*?)\\s*$', // recorded verdict
  ].join(''),
);

/**
 * Parses the rows of section 1 out of the committed report.
 *
 * @return {Array<object>}
 *   One entry per recomputable row.
 */
const parseSectionOne = () => {
  const lines = readFileSync(REPORT, 'utf8').split('\n');
  const start = lines.findIndex((l) => /^1\. /.test(l));
  const end = lines.findIndex((l, i) => i > start && /^2\. /.test(l));
  assert.ok(start !== -1, 'report has a section 1 heading');
  assert.ok(end !== -1, 'report has a section 2 heading to bound section 1');

  return lines
    .slice(start, end)
    .map((line) => line.match(ROW))
    .filter(Boolean)
    .map(
      ([
        ,
        globalTheme,
        sectionTheme,
        bgSlot,
        role,
        fgSlot,
        ratio,
        verdict,
      ]) => ({
        globalTheme,
        sectionTheme,
        bgSlot,
        role,
        fgSlot,
        ratio,
        verdict: verdict.trim(),
      }),
    );
};

test('the committed report actually contains rows to check', () => {
  const rows = parseSectionOne();
  // Guards against the regex silently matching nothing after a format change,
  // which would make every assertion below vacuously true.
  assert.ok(
    rows.length > 100,
    `Parsed only ${rows.length} rows from section 1 of section-background-contrast.txt. ` +
      "The report format probably changed and this test's ROW regex needs updating -- " +
      'do not leave it matching nothing, that silently disables the check.',
  );
});

test('every ratio the report records still matches the tokens', () => {
  const rows = parseSectionOne();
  const backgrounds = new Map(
    sectionBackgrounds().map((b) => [`${b.globalTheme}|${b.sectionTheme}`, b]),
  );

  // Array iteration rather than a for..of loop with `continue`: the shared
  // eslint config bars both (no-restricted-syntax, no-continue).
  const drift = rows
    .map((row) => {
      const bg = backgrounds.get(`${row.globalTheme}|${row.sectionTheme}`);
      if (!bg) {
        return `  ${row.globalTheme}/${row.sectionTheme}: pairing is in the report but no longer exists in the tokens`;
      }

      // Re-derive from the palette rather than trusting the hsl() the row
      // prints, so a token whose value moved is caught rather than echoed back.
      const fgValue = bg.slots[row.fgSlot];
      if (!fgValue) {
        return `  ${row.globalTheme}/${row.sectionTheme} ${row.role}: foreground ${row.fgSlot} no longer resolves`;
      }

      const actual = formatRatio(
        contrastRatio(parseHsl(bg.backgroundValue), parseHsl(fgValue)),
      );
      return actual === row.ratio
        ? null
        : `  ${row.globalTheme}/${row.sectionTheme} ${row.role} (${row.bgSlot} vs ${row.fgSlot}): ` +
            `report says ${row.ratio}:1, tokens now give ${actual}:1`;
    })
    .filter(Boolean);

  assert.equal(
    drift.join('\n'),
    '',
    `section-background-contrast.txt no longer matches the tokens it was generated from:\n${drift.join(
      '\n',
    )}\n` +
      '    Regenerate it rather than editing it:\n' +
      '      node components/00-tokens/colors/section-background-contrast.mjs \\\n' +
      '        > components/00-tokens/colors/section-background-contrast.txt\n' +
      '    Two SCSS comments cite this file as evidence (_yds-layout.scss, _yds-wrapped-callout.scss),\n' +
      '    so a stale copy is actively misleading, not merely out of date.',
  );
});

test('both reports still name the ticket and the script that generates them', () => {
  // Cheap provenance check. These headers are what tell a reader the file is
  // generated; losing them is how a generated file gets hand-edited.
  [REPORT, FUNCTIONAL_REPORT].forEach((file) => {
    const head = readFileSync(file, 'utf8').split('\n').slice(0, 12).join('\n');
    assert.match(
      head,
      /Generated by components\/00-tokens\/colors\/\S+\.mjs/,
      `${path.basename(file)} has lost the "Generated by ..." provenance line`,
    );
    assert.match(
      head,
      /YaleSites-Internal#\d+/,
      `${path.basename(file)} has lost its ticket reference`,
    );
  });
});
