name: Deploy Component Library
on:
  push:
    branches: ['main']
jobs:
  component-library-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        env:
          YALESITES_BUILD_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
      - name: Deploy storybook
        run: npm run storybook:deploy --  --source-branch main --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.YALESITES_BUILD_TOKEN }}
